### PR TITLE
Update to Rust 1.62.0

### PR DESCRIPTION
**Pull request by rouge8**
Rust 1.56.1 fixes a CVE (https://blog.rust-lang.org/2021/11/01/Rust-1.56.1.html) and is required for some packages: https://results.pre-commit.ci/run/github/1970795/1657566379.jpN4rJQVSxquC199vZ6zNQ

### CODE REVIEW

**Comment by asottile** [comment]
can you bump to latest stable instead?

**Comment by rouge8** [comment]
Done!

**Comment by rouge8** [comment]
@asottile when will this be live?

**Comment by asottile** [comment]
I've gotta deploy it still

**Pull request merged**
