### PR TITLE
bump .NET SDK to v6.0.200

### PR DESCRIPTION
**Pull request by rkm**

### CODE REVIEW

**Comment by rkm** [comment]
bah - the repo we're testing against (`dotnet/format`) doesn't seem to be regularly updated/released in order to support newer SDKs.

We could pick another one, or add a fake test project to this repo?

**Comment by asottile** [comment]
> bah - the repo we're testing against (`dotnet/format`) doesn't seem to be regularly updated/released in order to support newer SDKs.
> 
> We could pick another one, or add a fake test project to this repo?

either way -- whatever you'd prefer!  (though if `dotnet/format` will not work after this upgrade maybe we should wait?)

**Comment by rkm** [comment]
Yep, there's several related issues in their repo so let's wait and see. Feel free to close this in the meantime.

Would the ability to have pluggable / selectable language versions be something to investigate down the line, or is that out of scope for the free tier?

**Comment by asottile** [comment]
I think that would be best done as a feature to pre-commit itself (make `language_version` work)

**Comment by asottile** [comment]
I'm bumping to .net 7 so closing this out!

**Pull request closed without merging**
